#!/bin/bash

# Quick wrapper script to determine if Vector should show the regular bootanim or the verbose boot anim

INDEV_OR_RELEASE="$(cat /etc/rebuild-dev-or-indev)"

if [ ! -f /anki/bin/vic-bootAnim-verbose ]
    /anki/bin/vic-bootAnim-stock
fi

if [[ -d /anki-devtools || INDEV_OR_RELEASE == "indev" ]]; then
    /anki/bin/vic-bootAnim-verbose
else
    /anki/bin/vic-bootAnim-stock
fi